# Generated by Django 5.2.6 on 2025-10-03 21:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='descriptions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='descriptions_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='descriptions_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language_course_en',
            field=models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('kyrgyz', 'Kyrgyz')], default='kyrgyz', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language_course_ky',
            field=models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('kyrgyz', 'Kyrgyz')], default='kyrgyz', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language_course_ru',
            field=models.CharField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('kyrgyz', 'Kyrgyz')], default='kyrgyz', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_en',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('advanced', 'Advanced')], default='beginner', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_ky',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('advanced', 'Advanced')], default='beginner', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_ru',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('advanced', 'Advanced')], default='beginner', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_name_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_ky',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_ky',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='docs_lesson',
            field=models.FileField(blank=True, null=True, upload_to='lesson_docs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=64, null=True)),
                ('bio_ru', models.TextField(blank=True, max_length=64, null=True)),
                ('bio_en', models.TextField(blank=True, max_length=64, null=True)),
                ('bio_ky', models.TextField(blank=True, max_length=64, null=True)),
                ('progress', models.TextField(blank=True, null=True)),
                ('progress_ru', models.TextField(blank=True, null=True)),
                ('progress_en', models.TextField(blank=True, null=True)),
                ('progress_ky', models.TextField(blank=True, null=True)),
                ('certificate_count', models.PositiveIntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('enrolled_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_online.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=64, null=True)),
                ('bio_ru', models.TextField(blank=True, max_length=64, null=True)),
                ('bio_en', models.TextField(blank=True, max_length=64, null=True)),
                ('bio_ky', models.TextField(blank=True, max_length=64, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('specialization', models.CharField(max_length=64)),
                ('specialization_ru', models.CharField(max_length=64, null=True)),
                ('specialization_en', models.CharField(max_length=64, null=True)),
                ('specialization_ky', models.CharField(max_length=64, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
