# Generated by Django 5.2.6 on 2025-10-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_online', '0002_assignment_description_en_assignment_description_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='questions',
            new_name='exam_name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='questions_en',
            new_name='exam_name_en',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='questions_ky',
            new_name='exam_name_ky',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='questions_ru',
            new_name='exam_name_ru',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title_ru',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_online.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_online.course')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=64)),
                ('question_title_ru', models.CharField(max_length=64, null=True)),
                ('question_title_en', models.CharField(max_length=64, null=True)),
                ('question_title_ky', models.CharField(max_length=64, null=True)),
                ('passing_score', models.PositiveSmallIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_online.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=32)),
                ('option_title_ru', models.CharField(max_length=32, null=True)),
                ('option_title_en', models.CharField(max_length=32, null=True)),
                ('option_title_ky', models.CharField(max_length=32, null=True)),
                ('answer', models.BooleanField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='it_online.questions')),
            ],
        ),
    ]
