# Generated by Django 5.2.6 on 2025-10-09 21:45

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_online', '0003_rename_questions_exam_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='it_online.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='language_course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('kyrgyz', 'Kyrgyz')], default='kyrgyz', max_length=37),
        ),
        migrations.AlterField(
            model_name='course',
            name='language_course_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('kyrgyz', 'Kyrgyz')], default='kyrgyz', max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language_course_ky',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('kyrgyz', 'Kyrgyz')], default='kyrgyz', max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language_course_ru',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('english', 'English'), ('arabic', 'Arabic'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('kyrgyz', 'Kyrgyz')], default='kyrgyz', max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('advanced', 'Advanced')], default='beginner', max_length=24),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('advanced', 'Advanced')], default='beginner', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_ky',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('advanced', 'Advanced')], default='beginner', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_ru',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('beginner', 'Beginner'), ('middle', 'Middle'), ('advanced', 'Advanced')], default='beginner', max_length=24, null=True),
        ),
    ]
